"""Persistencia en Oracle. Las credenciales solo salen de variables de entorno."""
import os

from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

load_dotenv()

_engine = None
_aviso = ""


def _credenciales():
    return {
        "user": os.getenv("DB_USER", "").strip(),
        "password": os.getenv("DB_PASS", "").strip(),
        "host": os.getenv("DB_HOST", "").strip(),
        "port": os.getenv("DB_PORT", "1521").strip() or "1521",
        "service": os.getenv("DB_SERVICE", "").strip(),
    }


def oracle_configurado():
    c = _credenciales()
    return all((c["user"], c["password"], c["host"], c["service"]))


def obtener_engine():
    global _engine, _aviso
    if not oracle_configurado():
        _aviso = "Oracle no está configurado. Define DB_USER, DB_PASS, DB_HOST y DB_SERVICE en .env."
        return None
    if _engine is not None:
        return _engine
    c = _credenciales()
    url = (
        f"oracle+oracledb://{c['user']}:{c['password']}"
        f"@{c['host']}:{c['port']}/?service_name={c['service']}"
    )
    _engine = create_engine(url, pool_pre_ping=True)
    return _engine


def asegurar_tabla_aceptados(conn):
    conn.execute(text("""
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE factura_aceptada (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fecha_ejecucion VARCHAR2(12),
                    marca VARCHAR2(80),
                    modelo VARCHAR2(160),
                    cantidad NUMBER,
                    beneficiario VARCHAR2(200),
                    ci VARCHAR2(20),
                    costo_mas_alto NUMBER,
                    costo_total NUMBER,
                    marca_base VARCHAR2(80),
                    modelo_base VARCHAR2(160),
                    tipo VARCHAR2(30),
                    archivo VARCHAR2(240),
                    estado VARCHAR2(200)
                )';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
    """))


def asegurar_columna_estado(conn):
    conn.execute(text("""
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE factura_aceptada ADD (estado VARCHAR2(200))';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -1430 THEN
                    RAISE;
                END IF;
        END;
    """))


def aceptar_registros(filas):
    """Inserta el reporte editado. Hace rollback si una fila falla."""
    motor = obtener_engine()
    if motor is None:
        return False, _aviso or "Oracle no está configurado."
    if not filas:
        return False, "No hay filas para aceptar."
    try:
        with motor.begin() as conn:
            asegurar_tabla_aceptados(conn)
            asegurar_columna_estado(conn)
            conn.execute(
                text("""
                    INSERT INTO factura_aceptada (
                        fecha_ejecucion, marca, modelo, cantidad, beneficiario, ci,
                        costo_mas_alto, costo_total, marca_base, modelo_base, tipo, archivo, estado
                    ) VALUES (
                        :Fecha_Ejecucion, :Marca, :Modelo, :cantidad, :beneficiario, :ci,
                        :costo_mas_alto, :costo_total, :marca_base, :modelo_base, :Tipo, :archivo, :Estado
                    )
                """),
                [_fila_oracle(f) for f in filas],
            )
        return True, f"{len(filas)} registro(s) cargados en Oracle."
    except SQLAlchemyError as exc:
        return False, f"Oracle rechazó la carga y no se guardó nada: {exc}"


def _fila_oracle(fila):
    def txt(clave, n):
        return str(fila.get(clave) or "")[:n]

    def num(clave):
        try:
            return float(fila.get(clave) or 0)
        except (TypeError, ValueError):
            return 0.0

    return {
        "Fecha_Ejecucion": txt("Fecha_Ejecucion", 12),
        "Marca": txt("Marca", 80),
        "Modelo": txt("Modelo", 160),
        "cantidad": num("cantidad"),
        "beneficiario": txt("beneficiario", 200),
        "ci": txt("ci", 20),
        "costo_mas_alto": num("costo_mas_alto"),
        "costo_total": num("costo_total"),
        "marca_base": txt("marca_base", 80),
        "modelo_base": txt("modelo_base", 160),
        "Tipo": txt("Tipo", 30),
        "archivo": txt("archivo", 240),
        "Estado": txt("Estado", 200),
    }


def modelo_en_oracle(nombre):
    """True/False si Oracle responde. None si no hay conexión, para usar el catálogo local."""
    motor = obtener_engine()
    if motor is None:
        return None
    try:
        with motor.connect() as conn:
            fila = conn.execute(
                text("SELECT 1 FROM modelos WHERE UPPER(modelo) = UPPER(:n)"),
                {"n": nombre},
            ).first()
            return fila is not None
    except SQLAlchemyError:
        return None


def carroceria_oracle(modelo):
    motor = obtener_engine()
    if motor is None or not modelo:
        return None
    try:
        with motor.connect() as conn:
            fila = conn.execute(
                text("SELECT carroceria FROM modelos WHERE UPPER(modelo) = UPPER(:n)"),
                {"n": str(modelo).strip()},
            ).first()
            return fila[0] if fila else None
    except SQLAlchemyError:
        return None


def insertar_modelo_oracle(marca, modelo, carroceria):
    motor = obtener_engine()
    if motor is None:
        return "Catálogo local actualizado. Oracle no está configurado."
    try:
        with motor.begin() as conn:
            conn.execute(
                text(
                    "INSERT INTO modelos (marca, modelo, carroceria) "
                    "VALUES (:marca, :modelo, :carroceria)"
                ),
                {"marca": marca, "modelo": modelo, "carroceria": carroceria},
            )
        return "Modelo registrado en Oracle y en el catálogo local."
    except SQLAlchemyError as exc:
        return f"Quedó en el catálogo local. Oracle no insertó el modelo: {exc}"
